all: main

main: brick_game/snake/*

# main: brick_game/snake/s21_main.cpp brick_game/snake/s21_board.hpp brick_game/snake/s21_snake.hpp
	g++ brick_game/snake/s21_main.cpp -DUSE_NCURSES -lncurses -o main
